FROM hypriot/rpi-node:6.10.0 as build

# Build stage
WORKDIR /code
COPY package.json /code
COPY . /code
CMD ["node", "app.js"]


# Final stage
FROM hypriot/rpi-node:6.10.0-alpine
WORKDIR /code
RUN npm install --production
COPY --from=build code/ /code
CMD ["node", "bin/app.js"]
