#Build stage
FROM aarch64/node:6.9.1 as build
COPY qemu-aarch64-static /usr/bin/qemu-aarch64-static
WORKDIR /code
COPY package.json /code
RUN npm install --production
COPY . /code
CMD ["node", "app.js"]

#Final stage
FROM aarch64/node:6.9.1-slim
WORKDIR /code
COPY --from=build /code /code
COPY --from=build /usr/bin/qemu-aarch64-static /usr/bin/qemu-aarch64-static
CMD ["node", "bin/app.js"]
